# Generated by Django 6.0.2 on 2026-02-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('aod', models.FloatField(help_text='Aerosol Optical Depth')),
                ('no2', models.FloatField(help_text='Nitrogen Dioxide (ppb)')),
                ('so2', models.FloatField(help_text='Sulfur Dioxide (ppb)')),
                ('ndvi', models.FloatField(help_text='Vegetation Index')),
                ('temperature', models.FloatField(help_text='°C')),
                ('wind_speed', models.FloatField(help_text='km/h')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_params', to='api.city')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AQIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pm25', models.FloatField(help_text='PM2.5 concentration in µg/m³')),
                ('aqi', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Moderate', 'Moderate'), ('Unhealthy', 'Unhealthy'), ('Very Unhealthy', 'Very Unhealthy'), ('Hazardous', 'Hazardous')], default='Moderate', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.city')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', 'timestamp'], name='api_aqiread_city_id_f700cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForecastReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.PositiveSmallIntegerField(help_text='Forecast day offset (1–7)')),
                ('pm25', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='api.city')),
            ],
            options={
                'ordering': ['city', 'created_at', 'day'],
                'unique_together': {('city', 'created_at', 'day')},
            },
        ),
    ]
